[package]
name = "serial_test_test"
description = "External testing crate for serial_test"
license = "MIT"
version = "0.5.1"
authors = ["Tom Parker-Shemilt <palfrey@tevp.net>"]
edition = "2018"

[dev-dependencies]
serial_test = { path="../serial_test" }
lazy_static = "^1.2"
env_logger = ">= 0.7, <0.9"
tokio = { version = "0.2", features = ["macros", "rt-threaded"] } # Can't upgrade or we break 1.39
actix-rt = "1.0"